# Metadata for the site header and footer
title: विवेक श्रेष्ठ र अरु परोपकारी साथीहर्ले लेख्नुभको वेबसाइट
description: A website made with GitHub Pages

# Set the production website URL when previewing
baseurl: 

# Markdown parser and theme settings
markdown: kramdown
theme: minima
