# Metadata for the site header and footer
title: Vivek Stha n team written weblog
description: (P) matters DownTo ToJustDoIt, (T)-theory curiousCat Incase.

# Set the production website URL when previewing
baseurl: 

# Markdown parser and theme settings
markdown: kramdown
theme: minima
