# Metadata for the site header and footer
title: Vivek Shrestha website
description: A website made with GitHub Pages

# Set the production website URL when previewing
baseurl: 

# Markdown parser and theme settings
markdown: kramdown
theme: minima
