# Metadata for the site header and footer
title: RG, SM, UJ & Vivek Stha written weblog
description: (P)= JustDoIt, (T)=theory curiousCat Incase, (-a)=ForAmateurLearner, pros do differ

# Set the production website URL when previewing
baseurl:
# Markdown parser and theme settings
markdown: kramdown
theme: minima
